name: conlang_tools_common_lib
desc: Common Library for Tools, Softwares, and Systems of ConLangs' sake

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  matrix2d: ^1.0.0
  common_extensions:
    git: https://github.com/DevelopersPackages-org/CommonExtensions
